name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present

    # Start the server in the background using nohup and &
    - name: Start Server
      run: nohup npm start > server.log 2>&1 &

    # Wait for the server to be available before running tests
    - name: Wait for server
      run: |
        while ! curl -sSf http://localhost:4000; do
          echo "Waiting for the server to be available..."
          sleep 10  # Increase the waiting time to 10 seconds
        done

    # Run the tests with error handling
    - name: Run Tests
      run: npm test

    - name: Set up Docker Buildx
      run: docker buildx create --use

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build and push
      run: |
        docker buildx build \
          --push \
          --tag wallah/justme:latest \
          --platform linux/amd64,linux/arm64 \
          .
