name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["14.20.x"]
    services:
      # Define the Node.js service that runs the server
      server:
        image: node:${{ matrix.node-version }}
        ports:
          - 3000:3000
        options: --entrypoint "node" # Specify the entrypoint for the service
        command: "server.js" # Command to run the server.js file
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    # Wait for the server to be available before running tests
    - name: Wait for server
      run: |
        while ! curl -sSf http://localhost:3000; do
          echo "Waiting for the server to be available..."
          sleep 5
        done

    # Run the tests with error handling
    - name: Run Tests
      run: npm test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: wallah/justme:latest
