name: Node.js CI

on:
  push:
    branches: [main] # Trigger on push to the main branch
  pull_request:
    branches: [main] # Trigger on pull requests targeting the main branch

jobs:
  test: # Renamed the job to be more descriptive
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.20]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Consider testing without caching if issues arise
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: wallah/justme:latest
